# Generated by Django 4.0.4 on 2022-05-21 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muz_lk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muz',
            options={'ordering': ['-time_created'], 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AddField(
            model_name='muz',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
