# Generated by Django 4.0.4 on 2022-04-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boom',
            name='rating',
            field=models.ImageField(default='', upload_to='booms/images/'),
        ),
    ]
